export enum MOMENT_DATE_FORMAT {
    FULLTIMESTAMP = 'YYYY-MM-DD HH:mm:ss.SSS',
    TIMESTAMP = 'YYYY-MM-DD HH:mm:ss',
    DD = 'DD',
    DDMM = 'DD-MM',
    DDMMYYYY = 'DD-MM-YYYY',
    MM = 'MM',
    MMDD = 'MM-DD',
    MMDDYYYY = 'MM-DD-YYYY',
    YYYY='YYYY',
    YYYYMM = 'YYYY-MM',
    YYYYMMDD = 'YYYY-MM-DD',
    YYYYDDMM = 'YYYY-DD-MM',
    HHmmss = 'HH:mm:ss',
    HHmm = 'HH:mm',
    HH = 'HH',
    mm = 'mm',
    mmss = 'mm:ss',
    ss = 'ss',
  }